/*
Copyright 2026 Weidao Lee.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package internal

import (
	fmt "fmt"
	sync "sync"

	typed "sigs.k8s.io/structured-merge-diff/v6/typed"
)

func Parser() *typed.Parser {
	parserOnce.Do(func() {
		var err error
		parser, err = typed.NewParser(schemaYAML)
		if err != nil {
			panic(fmt.Sprintf("Failed to parse schema: %v", err))
		}
	})
	return parser
}

var parserOnce sync.Once
var parser *typed.Parser
var schemaYAML = typed.YAMLObject(`types:
- name: com.github.workload-identity.databricks-service-principal-operator.api.v1alpha1.DatabricksAccount
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    - name: spec
      type:
        namedType: com.github.workload-identity.databricks-service-principal-operator.api.v1alpha1.DatabricksAccountSpec
    - name: status
      type:
        namedType: com.github.workload-identity.databricks-service-principal-operator.api.v1alpha1.DatabricksAccountStatus
- name: com.github.workload-identity.databricks-service-principal-operator.api.v1alpha1.DatabricksAccountSpec
  map:
    fields:
    - name: accountId
      type:
        scalar: string
    - name: clientId
      type:
        scalar: string
    - name: host
      type:
        scalar: string
    - name: namespaces
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: associative
- name: com.github.workload-identity.databricks-service-principal-operator.api.v1alpha1.DatabricksAccountStatus
  map:
    fields:
    - name: audience
      type:
        scalar: string
    - name: clusterMarker
      type:
        scalar: string
    - name: conditions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
          elementRelationship: associative
          keys:
          - type
    - name: issuer
      type:
        scalar: string
    - name: subject
      type:
        scalar: string
- name: com.github.workload-identity.databricks-service-principal-operator.api.v1alpha1.DatabricksServiceAccount
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    - name: status
      type:
        namedType: com.github.workload-identity.databricks-service-principal-operator.api.v1alpha1.DatabricksServiceAccountStatus
- name: com.github.workload-identity.databricks-service-principal-operator.api.v1alpha1.DatabricksServiceAccountStatus
  map:
    fields:
    - name: identities
      type:
        list:
          elementType:
            namedType: com.github.workload-identity.databricks-service-principal-operator.api.v1alpha1.ProjectedIdentity
          elementRelationship: associative
          keys:
          - profile
- name: com.github.workload-identity.databricks-service-principal-operator.api.v1alpha1.IssuedDatabricksServicePrincipal
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    - name: spec
      type:
        namedType: com.github.workload-identity.databricks-service-principal-operator.api.v1alpha1.IssuedDatabricksServicePrincipalSpec
    - name: status
      type:
        namedType: com.github.workload-identity.databricks-service-principal-operator.api.v1alpha1.IssuedDatabricksServicePrincipalStatus
- name: com.github.workload-identity.databricks-service-principal-operator.api.v1alpha1.IssuedDatabricksServicePrincipalSpec
  map:
    fields:
    - name: identity
      type:
        scalar: string
    - name: serviceAccount
      type:
        namedType: com.github.workload-identity.databricks-service-principal-operator.api.v1alpha1.IssuedServiceAccount
    - name: subject
      type:
        scalar: string
- name: com.github.workload-identity.databricks-service-principal-operator.api.v1alpha1.IssuedDatabricksServicePrincipalStatus
  map:
    fields:
    - name: accountId
      type:
        scalar: string
    - name: audience
      type:
        scalar: string
    - name: clientId
      type:
        scalar: string
    - name: conditions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
          elementRelationship: associative
          keys:
          - type
    - name: issuer
      type:
        scalar: string
    - name: servicePrincipalCreateSentAt
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: servicePrincipalId
      type:
        scalar: string
    - name: servicePrincipalRemovedAt
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
- name: com.github.workload-identity.databricks-service-principal-operator.api.v1alpha1.IssuedServiceAccount
  map:
    fields:
    - name: name
      type:
        scalar: string
    - name: namespace
      type:
        scalar: string
    - name: namespaceUid
      type:
        namedType: io.k8s.apimachinery.pkg.types.UID
    - name: uid
      type:
        namedType: io.k8s.apimachinery.pkg.types.UID
- name: com.github.workload-identity.databricks-service-principal-operator.api.v1alpha1.ProjectedIdentity
  map:
    fields:
    - name: accountId
      type:
        scalar: string
    - name: audience
      type:
        scalar: string
    - name: clientId
      type:
        scalar: string
    - name: conditions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
          elementRelationship: associative
          keys:
          - type
    - name: issued
      type:
        scalar: string
    - name: operator
      type:
        scalar: string
    - name: profile
      type:
        scalar: string
    - name: servicePrincipalId
      type:
        scalar: string
    - name: servicePrincipalRemovedAt
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: subject
      type:
        scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
  map:
    fields:
    - name: lastTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: message
      type:
        scalar: string
    - name: observedGeneration
      type:
        scalar: numeric
    - name: reason
      type:
        scalar: string
    - name: status
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ConditionStatus
    - name: type
      type:
        scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ConditionStatus
  scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: fieldsType
      type:
        scalar: string
    - name: fieldsV1
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
    - name: manager
      type:
        scalar: string
    - name: operation
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsOperationType
    - name: subresource
      type:
        scalar: string
    - name: time
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsOperationType
  scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
  map:
    fields:
    - name: annotations
      type:
        map:
          elementType:
            scalar: string
    - name: creationTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: deletionGracePeriodSeconds
      type:
        scalar: numeric
    - name: deletionTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: finalizers
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: associative
    - name: generateName
      type:
        scalar: string
    - name: generation
      type:
        scalar: numeric
    - name: labels
      type:
        map:
          elementType:
            scalar: string
    - name: managedFields
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
          elementRelationship: atomic
    - name: name
      type:
        scalar: string
    - name: namespace
      type:
        scalar: string
    - name: ownerReferences
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
          elementRelationship: associative
          keys:
          - uid
    - name: resourceVersion
      type:
        scalar: string
    - name: selfLink
      type:
        scalar: string
    - name: uid
      type:
        namedType: io.k8s.apimachinery.pkg.types.UID
- name: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: blockOwnerDeletion
      type:
        scalar: boolean
    - name: controller
      type:
        scalar: boolean
    - name: kind
      type:
        scalar: string
    - name: name
      type:
        scalar: string
    - name: uid
      type:
        namedType: io.k8s.apimachinery.pkg.types.UID
    elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Time
  scalar: untyped
- name: io.k8s.apimachinery.pkg.types.UID
  scalar: string
- name: __untyped_atomic_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
- name: __untyped_deduced_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_deduced_
    elementRelationship: separable
`)
