---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - databricks.workload-identity.io
  resources:
  - databricksserviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - databricks.workload-identity.io
  resources:
  - databricksserviceaccounts/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: system
rules:
- apiGroups:
  - databricks.workload-identity.io
  resources:
  - databricksaccounts
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - databricks.workload-identity.io
  resources:
  - databricksaccounts/finalizers
  - issueddatabricksserviceprincipals/finalizers
  verbs:
  - update
- apiGroups:
  - databricks.workload-identity.io
  resources:
  - databricksaccounts/status
  - issueddatabricksserviceprincipals/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - databricks.workload-identity.io
  resources:
  - issueddatabricksserviceprincipals
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
