/*
Copyright 2026 Weidao Lee.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// DatabricksAccountStatusApplyConfiguration represents a declarative configuration of the DatabricksAccountStatus type for use
// with apply.
//
// DatabricksAccountStatus reports whether the operator can act in this account,
// and as whom.
type DatabricksAccountStatusApplyConfiguration struct {
	// subject is the sub claim the operator presents when it exchanges its
	// token. The federation policy in Databricks has to name this exact string.
	//
	// It is reported because it cannot be derived by reading anything the
	// installer has: it is assembled from the operator's namespace and
	// ServiceAccount name, both of which kustomize rewrites. Getting it wrong
	// produces a refusal that quotes the federation policy back, sending whoever
	// reads it to fix a policy that is correct. So the operator states who it is
	// rather than leaving it to be reconstructed.
	Subject *string `json:"subject,omitempty"`
	// audience is the aud claim on the token the operator presents, which the
	// federation policy must also name. It comes from the Deployment, not from
	// the spec above.
	Audience *string `json:"audience,omitempty"`
	// issuer is the cluster's OIDC issuer, which every federation policy this
	// operator writes names verbatim. It is what tells one cluster's identities
	// from another's in Databricks, where nothing else does: two clusters can
	// hold the same namespace and ServiceAccount names, so the subject alone
	// says nothing about which cluster a service principal answers to.
	Issuer *string `json:"issuer,omitempty"`
	// clusterMarker is the first twelve characters of every externalId this
	// operator writes: a hash of the issuer above, shared by every identity this
	// cluster made and by nothing else.
	//
	// Reported because a hash cannot be read backwards. An account admin holding
	// a service principal can see its externalId and get nothing from it; what
	// they can do is take this string and compare. So the cluster states its own
	// marker rather than leaving somebody to derive it, which means knowing the
	// issuer, the hash and the encoding.
	ClusterMarker *string `json:"clusterMarker,omitempty"`
	// conditions report whether this account is usable.
	//
	// Ready is true once the operator has exchanged its token and made one
	// account-level call. Until then no identity can be created, and each one
	// says so rather than failing in a way that looks like the ServiceAccount
	// having asked wrongly.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// DatabricksAccountStatusApplyConfiguration constructs a declarative configuration of the DatabricksAccountStatus type for use with
// apply.
func DatabricksAccountStatus() *DatabricksAccountStatusApplyConfiguration {
	return &DatabricksAccountStatusApplyConfiguration{}
}

// WithSubject sets the Subject field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Subject field is set to the value of the last call.
func (b *DatabricksAccountStatusApplyConfiguration) WithSubject(value string) *DatabricksAccountStatusApplyConfiguration {
	b.Subject = &value
	return b
}

// WithAudience sets the Audience field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Audience field is set to the value of the last call.
func (b *DatabricksAccountStatusApplyConfiguration) WithAudience(value string) *DatabricksAccountStatusApplyConfiguration {
	b.Audience = &value
	return b
}

// WithIssuer sets the Issuer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Issuer field is set to the value of the last call.
func (b *DatabricksAccountStatusApplyConfiguration) WithIssuer(value string) *DatabricksAccountStatusApplyConfiguration {
	b.Issuer = &value
	return b
}

// WithClusterMarker sets the ClusterMarker field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterMarker field is set to the value of the last call.
func (b *DatabricksAccountStatusApplyConfiguration) WithClusterMarker(value string) *DatabricksAccountStatusApplyConfiguration {
	b.ClusterMarker = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *DatabricksAccountStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *DatabricksAccountStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
