/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DatabricksServicePrincipalStatusApplyConfiguration represents a declarative configuration of the DatabricksServicePrincipalStatus type for use
// with apply.
//
// DatabricksServicePrincipalStatus is every identity this ServiceAccount was
// issued, as its owner can see them.
type DatabricksServicePrincipalStatusApplyConfiguration struct {
	// identities is one entry per identity, keyed by what was asked for.
	//
	// A list rather than an object per identity, so that the name of this object
	// stays the ServiceAccount's and needs no composition rule -- and so that one
	// object answers "what identities does this workload have" rather than
	// leaving somebody to find the others.
	Identities []ProjectedIdentityApplyConfiguration `json:"identities,omitempty"`
}

// DatabricksServicePrincipalStatusApplyConfiguration constructs a declarative configuration of the DatabricksServicePrincipalStatus type for use with
// apply.
func DatabricksServicePrincipalStatus() *DatabricksServicePrincipalStatusApplyConfiguration {
	return &DatabricksServicePrincipalStatusApplyConfiguration{}
}

// WithIdentities adds the given value to the Identities field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Identities field.
func (b *DatabricksServicePrincipalStatusApplyConfiguration) WithIdentities(values ...*ProjectedIdentityApplyConfiguration) *DatabricksServicePrincipalStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithIdentities")
		}
		b.Identities = append(b.Identities, *values[i])
	}
	return b
}
