/*
Copyright 2026 Weidao Lee.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/workload-identity/databricks-service-principal-operator/api/v1alpha1"
	internal "github.com/workload-identity/databricks-service-principal-operator/applyconfiguration/internal"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// DatabricksServiceAccountApplyConfiguration represents a declarative configuration of the DatabricksServiceAccount type for use
// with apply.
//
// DatabricksServiceAccount shows the owner of one ServiceAccount what this
// operator issued to it. It is a projection and it decides nothing.
//
// Every field on it was copied from an IssuedDatabricksServicePrincipal in the
// operator's own namespace, which is the record and the only one. This object
// carries no finalizer, and deleting it means nothing: it is rebuilt on the next
// pass, the way a status that was scribbled on is overwritten. Nothing about the
// identity in Databricks depends on it existing.
//
// It is here because the record is not, and cannot be: the record has to outlive
// the namespace that asked for the identity, and a person holding that namespace
// cannot be given the operator's own. So the facts are copied to where they can
// be read -- including why an identity is stuck, which is the thing its owner
// would otherwise have to ask the platform team for.
//
// The operator never reads this object to decide anything. The moment it did,
// this would stop being a projection and become a second record, and two records
// disagree eventually without anybody noticing.
//
// It has no spec. Everything is already addressable: the name and namespace say
// which ServiceAccount, and the annotation on that ServiceAccount is the
// request. A copy here would be new only in the sense of being able to disagree
// with its source.
//
// The name is load-bearing, and it is the ServiceAccount's. One object per
// ServiceAccount, named after it and in its namespace, is what makes "everything
// one ServiceAccount was issued is in one place" something the API server keeps
// true rather than something this operator has to. What is on it is a list --
// one entry per identity, keyed on the profile name -- because a ServiceAccount
// may hold several, which is why this object is not named for any one of them.
type DatabricksServiceAccountApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration    `json:",inline"`
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	Status                           *DatabricksServiceAccountStatusApplyConfiguration `json:"status,omitempty"`
}

// DatabricksServiceAccount constructs a declarative configuration of the DatabricksServiceAccount type for use with
// apply.
func DatabricksServiceAccount(name, namespace string) *DatabricksServiceAccountApplyConfiguration {
	b := &DatabricksServiceAccountApplyConfiguration{}
	b.WithName(name)
	b.WithNamespace(namespace)
	b.WithKind("DatabricksServiceAccount")
	b.WithAPIVersion("databricks.workload-identity.io/v1alpha1")
	return b
}

// ExtractDatabricksServiceAccountFrom extracts the applied configuration owned by fieldManager from
// databricksServiceAccount for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// databricksServiceAccount must be a unmodified DatabricksServiceAccount API object that was retrieved from the Kubernetes API.
// ExtractDatabricksServiceAccountFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractDatabricksServiceAccountFrom(databricksServiceAccount *apiv1alpha1.DatabricksServiceAccount, fieldManager string, subresource string) (*DatabricksServiceAccountApplyConfiguration, error) {
	b := &DatabricksServiceAccountApplyConfiguration{}
	err := managedfields.ExtractInto(databricksServiceAccount, internal.Parser().Type("com.github.workload-identity.databricks-service-principal-operator.api.v1alpha1.DatabricksServiceAccount"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(databricksServiceAccount.Name)
	b.WithNamespace(databricksServiceAccount.Namespace)

	b.WithKind("DatabricksServiceAccount")
	b.WithAPIVersion("databricks.workload-identity.io/v1alpha1")
	return b, nil
}

// ExtractDatabricksServiceAccount extracts the applied configuration owned by fieldManager from
// databricksServiceAccount. If no managedFields are found in databricksServiceAccount for fieldManager, a
// DatabricksServiceAccountApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// databricksServiceAccount must be a unmodified DatabricksServiceAccount API object that was retrieved from the Kubernetes API.
// ExtractDatabricksServiceAccount provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractDatabricksServiceAccount(databricksServiceAccount *apiv1alpha1.DatabricksServiceAccount, fieldManager string) (*DatabricksServiceAccountApplyConfiguration, error) {
	return ExtractDatabricksServiceAccountFrom(databricksServiceAccount, fieldManager, "")
}

// ExtractDatabricksServiceAccountStatus extracts the applied configuration owned by fieldManager from
// databricksServiceAccount for the status subresource.
func ExtractDatabricksServiceAccountStatus(databricksServiceAccount *apiv1alpha1.DatabricksServiceAccount, fieldManager string) (*DatabricksServiceAccountApplyConfiguration, error) {
	return ExtractDatabricksServiceAccountFrom(databricksServiceAccount, fieldManager, "status")
}

func (b DatabricksServiceAccountApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *DatabricksServiceAccountApplyConfiguration) WithKind(value string) *DatabricksServiceAccountApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *DatabricksServiceAccountApplyConfiguration) WithAPIVersion(value string) *DatabricksServiceAccountApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DatabricksServiceAccountApplyConfiguration) WithName(value string) *DatabricksServiceAccountApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *DatabricksServiceAccountApplyConfiguration) WithGenerateName(value string) *DatabricksServiceAccountApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *DatabricksServiceAccountApplyConfiguration) WithNamespace(value string) *DatabricksServiceAccountApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *DatabricksServiceAccountApplyConfiguration) WithUID(value types.UID) *DatabricksServiceAccountApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *DatabricksServiceAccountApplyConfiguration) WithResourceVersion(value string) *DatabricksServiceAccountApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *DatabricksServiceAccountApplyConfiguration) WithGeneration(value int64) *DatabricksServiceAccountApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *DatabricksServiceAccountApplyConfiguration) WithCreationTimestamp(value metav1.Time) *DatabricksServiceAccountApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *DatabricksServiceAccountApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *DatabricksServiceAccountApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *DatabricksServiceAccountApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *DatabricksServiceAccountApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *DatabricksServiceAccountApplyConfiguration) WithLabels(entries map[string]string) *DatabricksServiceAccountApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *DatabricksServiceAccountApplyConfiguration) WithAnnotations(entries map[string]string) *DatabricksServiceAccountApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *DatabricksServiceAccountApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *DatabricksServiceAccountApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *DatabricksServiceAccountApplyConfiguration) WithFinalizers(values ...string) *DatabricksServiceAccountApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *DatabricksServiceAccountApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *DatabricksServiceAccountApplyConfiguration) WithStatus(value *DatabricksServiceAccountStatusApplyConfiguration) *DatabricksServiceAccountApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *DatabricksServiceAccountApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *DatabricksServiceAccountApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *DatabricksServiceAccountApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *DatabricksServiceAccountApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
