/*
Copyright 2026 Weidao Lee.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DatabricksAccountSpecApplyConfiguration represents a declarative configuration of the DatabricksAccountSpec type for use
// with apply.
//
// DatabricksAccountSpec says which Databricks account the operator acts in, and
// as whom.
//
// It is the operator's own configuration rather than anything a workload
// declares, and it is namespaced so that changing it needs write access to the
// operator's own namespace -- which is already the access that could replace the
// operator's image or its ServiceAccount. Expressing it as a declaration rather
// than as startup arguments is what lets the operator answer back: whether the
// exchange works, and, when it does not, which subject and audience it was
// presenting.
//
// Nothing here is a secret, and it is deliberately not stored as one. A host is
// a URL. An account id is an identifier. clientId is the client_id of an OAuth
// client that has no client secret -- what gates the exchange is the federation
// policy in Databricks, naming an issuer, a subject and an audience. Holding
// these three values without the ability to mint a token from that issuer, for
// that subject, obtains nothing. Storing them as a Secret would assert they need
// protecting, and this project's claim is that nothing here does.
//
// Two values that belong to the operator rather than to the account are not
// here: where its projected token is mounted, and the audience that token
// carries. Both are set in the Deployment, because the audience has to agree
// with the projected volume beside it, and a value that must match its neighbour
// belongs next to it rather than in a separate object where nothing can compare
// them.
type DatabricksAccountSpecApplyConfiguration struct {
	// host is the Databricks account console host, such as
	// https://accounts.cloud.databricks.com.
	//
	// On unified deployments the account and its workspaces share one host, so
	// this is not always an "accounts." name.
	//
	// It cannot be changed, for the reason accountId cannot: one account has one
	// host, so an edit here is either a correction or a move, and a move is the
	// same thing accountId's own immutability refuses.
	Host *string `json:"host,omitempty"`
	// accountId identifies the Databricks account.
	//
	// databricks account users list -o json | jq -r '.[0].id'  # not this
	//
	// It is in the account console URL, and in the CLI's own profile:
	//
	// databricks auth describe -p <account profile>
	//
	// It cannot be changed. A service principal id means nothing outside the
	// account it was made in, so an operator pointed at another one would delete
	// something it never made, or read the 404 that means "not here" as the one
	// that means "gone" -- for every identity in the cluster, in one reconcile
	// interval, with nothing anywhere reporting an error.
	//
	// This is one of three doors, and closing it alone would not be worth much.
	// Deleting the object and creating another naming a different account is the
	// same edit with a longer handle, which is what AccountFinalizer refuses,
	// and pointing a running operator at a second object is a third, which is
	// checked when it starts. Together they make the account this operator acts
	// in fixed for its lifetime, and an id it wrote down always meaningful.
	AccountID *string `json:"accountId,omitempty"`
	// clientId is the applicationId of the service principal the operator acts
	// as -- not its numeric id, and not its display name.
	//
	// Token exchange without it fails as TOKEN_INVALID with the federation
	// policy's own description echoed back, which reads as though the policy
	// were wrong. It is not.
	ClientID *string `json:"clientId,omitempty"`
	// namespaces are the namespaces this operator issues identities in and
	// manages them in, by name.
	//
	// Taking a namespace off this list destroys every identity this account
	// issued there. The service principals are deleted in Databricks and every
	// grant anybody made on them goes with them, the records go, and the client
	// ids stop resolving to anything. It is not a pause and it cannot be
	// undone from here.
	//
	// Naming the namespace again is not a restore. It issues new service
	// principals with new client ids and no grants, and every grant made on the
	// ones that were destroyed has to be made again by whoever made it.
	//
	// The guarantee is eventual, not instant. The destruction is carried out
	// against Databricks, so while Databricks cannot be reached the namespace is
	// off this list and the identities it issued there still exist. The
	// IdentitiesDestroyed condition on this object says how many are left and in
	// which namespaces, and it is what says whether the destruction has finished.
	//
	// What the list means, in the three states a namespace can be in: on it,
	// this account issues identities there and manages them; taken off it, every
	// identity this account issued there is destroyed; never on it, nothing
	// there belongs to this account. That buys one thing a person can check --
	// every service principal carrying this operator's marker is in a namespace
	// on this list.
	//
	// This is where a platform team says what their account admin credential may
	// be spent on. It is theirs and nobody else's: the object lives in their own
	// namespace, and no namespace can add itself to it.
	//
	// Empty serves nothing, and that is the default rather than an oversight. A
	// permissive default would have an operator installed for one team quietly
	// answering every ServiceAccount in the cluster that happened to name it.
	// Emptying a list that had entries in it destroys the identities in every one
	// of them.
	//
	// The order the destruction is carried out in is the whole of why it is safe
	// to interrupt. The operator suspends minting in the namespace first -- it
	// labels the Namespace with its own name, which is a claim no second operator
	// can take while it is held -- and only then destroys, because a destruction
	// begun while identities can still be minted there would leave behind the
	// ones minted after it. Then it lifts the label, and whoever else serves the
	// namespace goes on minting with nothing for a person to do. A token already
	// in a running pod is not recalled by any of this -- the pod holds it, and it
	// stops working because the service principal it names is gone.
	//
	// Names rather than a label selector. Neither is safer -- a namespace coming
	// into scope still needs the cluster's mint label open and a ServiceAccount
	// naming this operator -- so the choice is auditability against flexibility.
	// A list answers "which namespaces does this operator serve" by being read. A
	// selector answers it only by being evaluated against every namespace in the
	// cluster, at the moment somebody asks, and the answer changes when somebody
	// who is not on that team relabels a namespace.
	Namespaces []string `json:"namespaces,omitempty"`
}

// DatabricksAccountSpecApplyConfiguration constructs a declarative configuration of the DatabricksAccountSpec type for use with
// apply.
func DatabricksAccountSpec() *DatabricksAccountSpecApplyConfiguration {
	return &DatabricksAccountSpecApplyConfiguration{}
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *DatabricksAccountSpecApplyConfiguration) WithHost(value string) *DatabricksAccountSpecApplyConfiguration {
	b.Host = &value
	return b
}

// WithAccountID sets the AccountID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccountID field is set to the value of the last call.
func (b *DatabricksAccountSpecApplyConfiguration) WithAccountID(value string) *DatabricksAccountSpecApplyConfiguration {
	b.AccountID = &value
	return b
}

// WithClientID sets the ClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientID field is set to the value of the last call.
func (b *DatabricksAccountSpecApplyConfiguration) WithClientID(value string) *DatabricksAccountSpecApplyConfiguration {
	b.ClientID = &value
	return b
}

// WithNamespaces adds the given value to the Namespaces field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Namespaces field.
func (b *DatabricksAccountSpecApplyConfiguration) WithNamespaces(values ...string) *DatabricksAccountSpecApplyConfiguration {
	for i := range values {
		b.Namespaces = append(b.Namespaces, values[i])
	}
	return b
}
