/*
Copyright 2026 Weidao Lee.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// IssuedDatabricksServicePrincipalStatusApplyConfiguration represents a declarative configuration of the IssuedDatabricksServicePrincipalStatus type for use
// with apply.
//
// IssuedDatabricksServicePrincipalStatus is what Databricks holds for this
// record now.
type IssuedDatabricksServicePrincipalStatusApplyConfiguration struct {
	// accountId is the Databricks account this record was acted on in.
	//
	// It is recorded because an id means nothing anywhere else: an operator
	// pointed at another account would delete something it never made, or read
	// the 404 that means "not here" as the one that means "gone".
	//
	// It is in the status rather than the spec because the account is not known
	// to whoever writes the record -- the DatabricksServiceAccount controller
	// knows a ServiceAccount is asking and nothing about Databricks. It is
	// written before the first call is made, not with the answer, so that a pass
	// which creates a service principal and then stops has already said where to
	// look for it.
	AccountID *string `json:"accountId,omitempty"`
	// servicePrincipalId is the numeric id Databricks assigned. Federation
	// policies hang off it, and it is what deletes it.
	//
	// Empty for one window only: between this record being written and the
	// create returning. What closes that window is the marker -- the service
	// principal carries it from the moment it exists, so one created by a pass
	// that then crashed is found again rather than left behind.
	//
	// A string rather than an integer because these are int64 and already
	// approach the largest integer JSON carries exactly.
	ServicePrincipalID *string `json:"servicePrincipalId,omitempty"`
	// clientId is the applicationId Databricks assigned, which the workload
	// presents when it exchanges its token, and which anything granting
	// permissions to this workload names.
	//
	// It cannot be derived: Databricks generates it and refuses to accept one.
	ClientID *string `json:"clientId,omitempty"`
	// issuer and audience are the other two things the federation policy
	// matches, recorded as they were sent.
	Issuer   *string `json:"issuer,omitempty"`
	Audience *string `json:"audience,omitempty"`
	// removedServicePrincipalId is an id this operator created and that is no
	// longer in Databricks.
	//
	// Databricks is where identity is governed. One deleted there was deleted by
	// somebody entitled to, and making a new one while the annotation still
	// stands would be this operator overruling them every minute, and winning,
	// since it never tires. So it is recorded and left.
	//
	// The id is kept rather than a flag because it is the value to search
	// Databricks' audit log with: that says who deleted it and when. A flag
	// would say something is wrong; an id says whom to ask.
	RemovedServicePrincipalID *string `json:"removedServicePrincipalId,omitempty"`
	// conditions report whether the service principal is there and whether a
	// federation policy trusts this subject.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// IssuedDatabricksServicePrincipalStatusApplyConfiguration constructs a declarative configuration of the IssuedDatabricksServicePrincipalStatus type for use with
// apply.
func IssuedDatabricksServicePrincipalStatus() *IssuedDatabricksServicePrincipalStatusApplyConfiguration {
	return &IssuedDatabricksServicePrincipalStatusApplyConfiguration{}
}

// WithAccountID sets the AccountID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccountID field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalStatusApplyConfiguration) WithAccountID(value string) *IssuedDatabricksServicePrincipalStatusApplyConfiguration {
	b.AccountID = &value
	return b
}

// WithServicePrincipalID sets the ServicePrincipalID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServicePrincipalID field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalStatusApplyConfiguration) WithServicePrincipalID(value string) *IssuedDatabricksServicePrincipalStatusApplyConfiguration {
	b.ServicePrincipalID = &value
	return b
}

// WithClientID sets the ClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientID field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalStatusApplyConfiguration) WithClientID(value string) *IssuedDatabricksServicePrincipalStatusApplyConfiguration {
	b.ClientID = &value
	return b
}

// WithIssuer sets the Issuer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Issuer field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalStatusApplyConfiguration) WithIssuer(value string) *IssuedDatabricksServicePrincipalStatusApplyConfiguration {
	b.Issuer = &value
	return b
}

// WithAudience sets the Audience field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Audience field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalStatusApplyConfiguration) WithAudience(value string) *IssuedDatabricksServicePrincipalStatusApplyConfiguration {
	b.Audience = &value
	return b
}

// WithRemovedServicePrincipalID sets the RemovedServicePrincipalID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemovedServicePrincipalID field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalStatusApplyConfiguration) WithRemovedServicePrincipalID(value string) *IssuedDatabricksServicePrincipalStatusApplyConfiguration {
	b.RemovedServicePrincipalID = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *IssuedDatabricksServicePrincipalStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *IssuedDatabricksServicePrincipalStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
