/*
Copyright 2026 Weidao Lee.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	types "k8s.io/apimachinery/pkg/types"
)

// IssuedServiceAccountApplyConfiguration represents a declarative configuration of the IssuedServiceAccount type for use
// with apply.
//
// IssuedServiceAccount is the ServiceAccount an identity was issued to, named
// so that a later one of the same name is not mistaken for it.
//
// The names are what Databricks matches: the subject in a federation policy is
// system:serviceaccount:<namespace>:<name>, and names get reused. The UIDs are
// what says whether the ServiceAccount answering to those names today is the
// one this was issued to. A namespace deleted and recreated under the same name
// is a different namespace, and every identity issued to the old one has to be
// destroyed rather than inherited.
type IssuedServiceAccountApplyConfiguration struct {
	// namespace and name are the ServiceAccount's, and are what the subject in
	// Databricks is assembled from.
	Namespace *string `json:"namespace,omitempty"`
	Name      *string `json:"name,omitempty"`
	// uid is the ServiceAccount's. It is what every comparison is made on: the
	// name of this record, the marker written into Databricks, and the question
	// asked every pass of whether the ServiceAccount answering to these names
	// today is the one this was issued to.
	//
	// One value is enough. A uid is unique across the cluster and across time,
	// so a namespace recreated under its old name holds ServiceAccounts whose
	// uids are new whatever their names are.
	UID *types.UID `json:"uid,omitempty"`
	// namespaceUid is the namespace's, and nothing decides on it.
	//
	// It is recorded because it answers a question a person asks of a record
	// that has outlived what it names -- was this namespace recreated, or was it
	// only this ServiceAccount -- and because it cannot drift: nothing
	// recomputes it and nothing writes it twice.
	NamespaceUID *types.UID `json:"namespaceUid,omitempty"`
}

// IssuedServiceAccountApplyConfiguration constructs a declarative configuration of the IssuedServiceAccount type for use with
// apply.
func IssuedServiceAccount() *IssuedServiceAccountApplyConfiguration {
	return &IssuedServiceAccountApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *IssuedServiceAccountApplyConfiguration) WithNamespace(value string) *IssuedServiceAccountApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *IssuedServiceAccountApplyConfiguration) WithName(value string) *IssuedServiceAccountApplyConfiguration {
	b.Name = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *IssuedServiceAccountApplyConfiguration) WithUID(value types.UID) *IssuedServiceAccountApplyConfiguration {
	b.UID = &value
	return b
}

// WithNamespaceUID sets the NamespaceUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NamespaceUID field is set to the value of the last call.
func (b *IssuedServiceAccountApplyConfiguration) WithNamespaceUID(value types.UID) *IssuedServiceAccountApplyConfiguration {
	b.NamespaceUID = &value
	return b
}
