/*
Copyright 2026 Weidao Lee.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/workload-identity/databricks-service-principal-operator/api/v1alpha1"
	internal "github.com/workload-identity/databricks-service-principal-operator/applyconfiguration/internal"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// IssuedDatabricksServicePrincipalApplyConfiguration represents a declarative configuration of the IssuedDatabricksServicePrincipal type for use
// with apply.
//
// IssuedDatabricksServicePrincipal is this operator's record that it created a
// service principal in Databricks. It is the only one.
//
// It lives in the operator's own namespace, and that is the whole point. What it
// records outlives the namespace that asked for it: a service principal is in
// Databricks, and deleting a Kubernetes namespace does not reach it. A record
// kept inside that namespace is deleted with it, in an order nothing specifies,
// and what survives is an identity nothing in the cluster remembers -- which the
// next occupant of that namespace name inherits, because a federation policy
// names a subject and a subject is a name that gets reused.
//
// So this record is not deleted by anything happening in a tenant's namespace.
// It is asked, every pass, whether the ServiceAccount it was issued to is still
// there, still asking, and still the same one. When the answer is no it deletes
// itself, and its finalizer deletes the service principal on the way out.
// Nothing about that depends on an event having been seen, on which kind a
// namespace teardown deleted first, or on the operator having been running at
// the time.
//
// Deleting this object destroys the identity. That is what it means, and it is
// the only object here that means it. The DatabricksServiceAccount in the
// tenant's namespace is a projection of this one: it can be deleted, and it
// comes back.
//
// Nobody writes one of these. The name is derived and the spec is immutable.
type IssuedDatabricksServicePrincipalApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration    `json:",inline"`
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	Spec                             *IssuedDatabricksServicePrincipalSpecApplyConfiguration   `json:"spec,omitempty"`
	Status                           *IssuedDatabricksServicePrincipalStatusApplyConfiguration `json:"status,omitempty"`
}

// IssuedDatabricksServicePrincipal constructs a declarative configuration of the IssuedDatabricksServicePrincipal type for use with
// apply.
func IssuedDatabricksServicePrincipal(name, namespace string) *IssuedDatabricksServicePrincipalApplyConfiguration {
	b := &IssuedDatabricksServicePrincipalApplyConfiguration{}
	b.WithName(name)
	b.WithNamespace(namespace)
	b.WithKind("IssuedDatabricksServicePrincipal")
	b.WithAPIVersion("databricks.workload-identity.io/v1alpha1")
	return b
}

// ExtractIssuedDatabricksServicePrincipalFrom extracts the applied configuration owned by fieldManager from
// issuedDatabricksServicePrincipal for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// issuedDatabricksServicePrincipal must be a unmodified IssuedDatabricksServicePrincipal API object that was retrieved from the Kubernetes API.
// ExtractIssuedDatabricksServicePrincipalFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractIssuedDatabricksServicePrincipalFrom(issuedDatabricksServicePrincipal *apiv1alpha1.IssuedDatabricksServicePrincipal, fieldManager string, subresource string) (*IssuedDatabricksServicePrincipalApplyConfiguration, error) {
	b := &IssuedDatabricksServicePrincipalApplyConfiguration{}
	err := managedfields.ExtractInto(issuedDatabricksServicePrincipal, internal.Parser().Type("com.github.workload-identity.databricks-service-principal-operator.api.v1alpha1.IssuedDatabricksServicePrincipal"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(issuedDatabricksServicePrincipal.Name)
	b.WithNamespace(issuedDatabricksServicePrincipal.Namespace)

	b.WithKind("IssuedDatabricksServicePrincipal")
	b.WithAPIVersion("databricks.workload-identity.io/v1alpha1")
	return b, nil
}

// ExtractIssuedDatabricksServicePrincipal extracts the applied configuration owned by fieldManager from
// issuedDatabricksServicePrincipal. If no managedFields are found in issuedDatabricksServicePrincipal for fieldManager, a
// IssuedDatabricksServicePrincipalApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// issuedDatabricksServicePrincipal must be a unmodified IssuedDatabricksServicePrincipal API object that was retrieved from the Kubernetes API.
// ExtractIssuedDatabricksServicePrincipal provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractIssuedDatabricksServicePrincipal(issuedDatabricksServicePrincipal *apiv1alpha1.IssuedDatabricksServicePrincipal, fieldManager string) (*IssuedDatabricksServicePrincipalApplyConfiguration, error) {
	return ExtractIssuedDatabricksServicePrincipalFrom(issuedDatabricksServicePrincipal, fieldManager, "")
}

// ExtractIssuedDatabricksServicePrincipalStatus extracts the applied configuration owned by fieldManager from
// issuedDatabricksServicePrincipal for the status subresource.
func ExtractIssuedDatabricksServicePrincipalStatus(issuedDatabricksServicePrincipal *apiv1alpha1.IssuedDatabricksServicePrincipal, fieldManager string) (*IssuedDatabricksServicePrincipalApplyConfiguration, error) {
	return ExtractIssuedDatabricksServicePrincipalFrom(issuedDatabricksServicePrincipal, fieldManager, "status")
}

func (b IssuedDatabricksServicePrincipalApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalApplyConfiguration) WithKind(value string) *IssuedDatabricksServicePrincipalApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalApplyConfiguration) WithAPIVersion(value string) *IssuedDatabricksServicePrincipalApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalApplyConfiguration) WithName(value string) *IssuedDatabricksServicePrincipalApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalApplyConfiguration) WithGenerateName(value string) *IssuedDatabricksServicePrincipalApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalApplyConfiguration) WithNamespace(value string) *IssuedDatabricksServicePrincipalApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalApplyConfiguration) WithUID(value types.UID) *IssuedDatabricksServicePrincipalApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalApplyConfiguration) WithResourceVersion(value string) *IssuedDatabricksServicePrincipalApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalApplyConfiguration) WithGeneration(value int64) *IssuedDatabricksServicePrincipalApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalApplyConfiguration) WithCreationTimestamp(value metav1.Time) *IssuedDatabricksServicePrincipalApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *IssuedDatabricksServicePrincipalApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *IssuedDatabricksServicePrincipalApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *IssuedDatabricksServicePrincipalApplyConfiguration) WithLabels(entries map[string]string) *IssuedDatabricksServicePrincipalApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *IssuedDatabricksServicePrincipalApplyConfiguration) WithAnnotations(entries map[string]string) *IssuedDatabricksServicePrincipalApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *IssuedDatabricksServicePrincipalApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *IssuedDatabricksServicePrincipalApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *IssuedDatabricksServicePrincipalApplyConfiguration) WithFinalizers(values ...string) *IssuedDatabricksServicePrincipalApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *IssuedDatabricksServicePrincipalApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalApplyConfiguration) WithSpec(value *IssuedDatabricksServicePrincipalSpecApplyConfiguration) *IssuedDatabricksServicePrincipalApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalApplyConfiguration) WithStatus(value *IssuedDatabricksServicePrincipalStatusApplyConfiguration) *IssuedDatabricksServicePrincipalApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *IssuedDatabricksServicePrincipalApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *IssuedDatabricksServicePrincipalApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *IssuedDatabricksServicePrincipalApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *IssuedDatabricksServicePrincipalApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
