/*
Copyright 2026 Weidao Lee.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// IssuedDatabricksServicePrincipalStatusApplyConfiguration represents a declarative configuration of the IssuedDatabricksServicePrincipalStatus type for use
// with apply.
//
// IssuedDatabricksServicePrincipalStatus is what Databricks holds for this
// record now.
type IssuedDatabricksServicePrincipalStatusApplyConfiguration struct {
	// accountId is the Databricks account this record was acted on in.
	//
	// It is where somebody reads off which account to search for the service
	// principal below, and it is the only thing an operator compares at startup:
	// one of these naming an account other than the one it was told to use is an
	// operator that refuses to serve, because an id means nothing outside the
	// account it was made in. Nothing else branches on it -- the account this
	// operator acts in is fixed for its lifetime, so every record it can see
	// belongs to it.
	//
	// It is in the status rather than the spec because the account is not known
	// to whoever writes the record -- the DatabricksServiceAccount controller
	// knows a ServiceAccount is asking and nothing about Databricks. It is
	// written before the first call is made, not with the answer, so that a pass
	// which creates a service principal and then stops has already said where to
	// look for it. A record that never sent one names no account, which is what
	// makes an operator that never reached Databricks free to be uninstalled.
	AccountID *string `json:"accountId,omitempty"`
	// servicePrincipalCreateSentAt is when this operator was about to ask
	// Databricks for the service principal below. It is written before the call
	// is made and never cleared.
	//
	// It is the one fact about this record that cannot be worked out again. The
	// marker, the subject and the display name are all derivable from the spec
	// at any moment; whether a create was already sent is not. Without it, a
	// record naming no id cannot be told from one whose create ran and whose
	// answer never arrived -- and those two permit opposite acts, since the
	// first may create and may be let go of, and the second may do neither.
	//
	// A moment rather than a flag, because a record waiting for that answer has
	// to be able to say how long it has been waiting.
	ServicePrincipalCreateSentAt *v1.Time `json:"servicePrincipalCreateSentAt,omitempty"`
	// servicePrincipalId is the numeric id Databricks assigned. Federation
	// policies hang off it, and it is what deletes it.
	//
	// Empty for one window only: between the create being sent and its answer
	// being written down. What closes that window is the marker -- the service
	// principal carries it from the moment it exists, so one created by a pass
	// that then crashed is found again rather than left behind.
	//
	// Written once and never cleared, including when Databricks answers that it
	// is gone. It is the value somebody searches the audit log with to find out
	// who deleted it, so clearing it would be the evidence of a removal
	// destroying the evidence it was drawn from.
	//
	// A string rather than an integer because these are int64 and already
	// approach the largest integer JSON carries exactly.
	ServicePrincipalID *string `json:"servicePrincipalId,omitempty"`
	// clientId is the applicationId Databricks assigned, which the workload
	// presents when it exchanges its token, and which anything granting
	// permissions to this workload names.
	//
	// It cannot be derived: Databricks generates it and refuses to accept one.
	ClientID *string `json:"clientId,omitempty"`
	// issuer and audience are the other two things the federation policy
	// matches, recorded as they were sent.
	Issuer   *string `json:"issuer,omitempty"`
	Audience *string `json:"audience,omitempty"`
	// servicePrincipalRemovedAt is when a get by id answered that the service
	// principal above is not there.
	//
	// Databricks is where identity is governed. One deleted there was deleted by
	// somebody entitled to, and making a new one while the annotation still
	// stands would be this operator overruling them every minute, and winning,
	// since it never tires. So it is recorded and left.
	//
	// Only the moment, because the id it is about is still in servicePrincipalId
	// and stays there: that is the value to search Databricks' audit log with,
	// and it says who deleted it and when. The two together bracket a service
	// principal's life, which is what makes what this record knows readable off
	// the status rather than guessed at from which field happens to be empty.
	ServicePrincipalRemovedAt *v1.Time `json:"servicePrincipalRemovedAt,omitempty"`
	// conditions report whether the service principal is there and whether a
	// federation policy trusts this subject.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// IssuedDatabricksServicePrincipalStatusApplyConfiguration constructs a declarative configuration of the IssuedDatabricksServicePrincipalStatus type for use with
// apply.
func IssuedDatabricksServicePrincipalStatus() *IssuedDatabricksServicePrincipalStatusApplyConfiguration {
	return &IssuedDatabricksServicePrincipalStatusApplyConfiguration{}
}

// WithAccountID sets the AccountID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccountID field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalStatusApplyConfiguration) WithAccountID(value string) *IssuedDatabricksServicePrincipalStatusApplyConfiguration {
	b.AccountID = &value
	return b
}

// WithServicePrincipalCreateSentAt sets the ServicePrincipalCreateSentAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServicePrincipalCreateSentAt field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalStatusApplyConfiguration) WithServicePrincipalCreateSentAt(value v1.Time) *IssuedDatabricksServicePrincipalStatusApplyConfiguration {
	b.ServicePrincipalCreateSentAt = &value
	return b
}

// WithServicePrincipalID sets the ServicePrincipalID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServicePrincipalID field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalStatusApplyConfiguration) WithServicePrincipalID(value string) *IssuedDatabricksServicePrincipalStatusApplyConfiguration {
	b.ServicePrincipalID = &value
	return b
}

// WithClientID sets the ClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientID field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalStatusApplyConfiguration) WithClientID(value string) *IssuedDatabricksServicePrincipalStatusApplyConfiguration {
	b.ClientID = &value
	return b
}

// WithIssuer sets the Issuer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Issuer field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalStatusApplyConfiguration) WithIssuer(value string) *IssuedDatabricksServicePrincipalStatusApplyConfiguration {
	b.Issuer = &value
	return b
}

// WithAudience sets the Audience field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Audience field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalStatusApplyConfiguration) WithAudience(value string) *IssuedDatabricksServicePrincipalStatusApplyConfiguration {
	b.Audience = &value
	return b
}

// WithServicePrincipalRemovedAt sets the ServicePrincipalRemovedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServicePrincipalRemovedAt field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalStatusApplyConfiguration) WithServicePrincipalRemovedAt(value v1.Time) *IssuedDatabricksServicePrincipalStatusApplyConfiguration {
	b.ServicePrincipalRemovedAt = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *IssuedDatabricksServicePrincipalStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *IssuedDatabricksServicePrincipalStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
