/*
Copyright 2026 Weidao Lee.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// IssuedDatabricksServicePrincipalSpecApplyConfiguration represents a declarative configuration of the IssuedDatabricksServicePrincipalSpec type for use
// with apply.
//
// IssuedDatabricksServicePrincipalSpec is what was issued and to whom. It is
// written once, when the record is made, and never changed.
//
// It is a spec rather than a status because it is not an observation of
// anything. Nothing recomputes these values and nothing reconciles towards
// them: they are what was true at the moment this operator created a service
// principal, and their whole use is to be compared against what is true now.
type IssuedDatabricksServicePrincipalSpecApplyConfiguration struct {
	// subject is the sub claim written into the federation policy, verbatim.
	//
	// Stored rather than reassembled from the names above. It is what Databricks
	// holds, and comparing the two sides means comparing what was actually sent,
	// not what would be sent if it were sent today.
	Subject *string `json:"subject,omitempty"`
	// serviceAccount is who this was issued to.
	ServiceAccount *IssuedServiceAccountApplyConfiguration `json:"serviceAccount,omitempty"`
	// identity is what the ServiceAccount called this one, and is empty when it
	// named none.
	//
	// It is what tells this record from the others issued to the same
	// ServiceAccount by the same operator. Every pass asks whether the
	// annotation still names it, and without this that question could only be
	// asked of the ServiceAccount as a whole -- so dropping one identity would
	// destroy them all, or none.
	//
	// Empty is a value here, not a missing one: it is the identity asked for by
	// naming no name, which is what nearly every ServiceAccount does.
	Identity *string `json:"identity,omitempty"`
}

// IssuedDatabricksServicePrincipalSpecApplyConfiguration constructs a declarative configuration of the IssuedDatabricksServicePrincipalSpec type for use with
// apply.
func IssuedDatabricksServicePrincipalSpec() *IssuedDatabricksServicePrincipalSpecApplyConfiguration {
	return &IssuedDatabricksServicePrincipalSpecApplyConfiguration{}
}

// WithSubject sets the Subject field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Subject field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalSpecApplyConfiguration) WithSubject(value string) *IssuedDatabricksServicePrincipalSpecApplyConfiguration {
	b.Subject = &value
	return b
}

// WithServiceAccount sets the ServiceAccount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccount field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalSpecApplyConfiguration) WithServiceAccount(value *IssuedServiceAccountApplyConfiguration) *IssuedDatabricksServicePrincipalSpecApplyConfiguration {
	b.ServiceAccount = value
	return b
}

// WithIdentity sets the Identity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Identity field is set to the value of the last call.
func (b *IssuedDatabricksServicePrincipalSpecApplyConfiguration) WithIdentity(value string) *IssuedDatabricksServicePrincipalSpecApplyConfiguration {
	b.Identity = &value
	return b
}
