/*
Copyright 2026 Weidao Lee.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ProjectedIdentityApplyConfiguration represents a declarative configuration of the ProjectedIdentity type for use
// with apply.
//
// ProjectedIdentity is one identity this ServiceAccount was issued, copied from
// the record that holds it.
//
// Everything here was written by the operator that issued it, and only by that
// one. A ServiceAccount asking two operators gets two of these on one object,
// each owned by its own writer -- which is what stops the two from undoing each
// other, the way two operators writing one DatabricksAccount's status once did.
type ProjectedIdentityApplyConfiguration struct {
	// profile is what a workload passes to the Databricks SDK to use this
	// identity: the name its own ServiceAccount gave it, or -- for the identity
	// asked for without one -- the operator's reference, which is a name nobody
	// typed and nothing derives. A rule for deriving it would be a rule the
	// workload had to learn before it could name its own profile.
	//
	// It is also the key this list merges on, so one operator writes one entry
	// and cannot touch another's. That holds without anything checking it: a
	// name is an annotation map key on this one ServiceAccount, so it is unique
	// here, and no name can collide with an operator reference because no name
	// holds the "/" that every reference holds. See Request.String.
	Profile *string `json:"profile,omitempty"`
	// operator is the DatabricksAccount naming the operator that issued this, as
	// <its namespace>/<its name> -- the value the ServiceAccount wrote in the
	// annotation key that asked for it, echoed back.
	//
	// Stored rather than read out of the key, and that is what the field is for.
	// The key is the profile name, which for a named identity is the name alone,
	// so an operator looking for its own reference inside the key would find its
	// unnamed entries and none of its named ones -- and every named one it had
	// stopped maintaining would be left on the object still reporting Ready.
	// Whose an entry is is a fact, so it is kept as one. See
	// ProjectedIdentity.AskedOf.
	Operator *string `json:"operator,omitempty"`
	// issued names the record this was copied from, as
	// <the operator's namespace>/<the record's name>, which is enough to reach
	// it: kubectl -n <that namespace> get isdbxsp <that name>.
	//
	// Reported because that record is what this operator acts on and this object
	// is not, and its name is derived from a uid, so it cannot be guessed.
	Issued *string `json:"issued,omitempty"`
	// servicePrincipalId is the numeric id Databricks assigned. Federation
	// policies hang off it.
	//
	// A string rather than an integer because these are int64 and already
	// approach the largest integer JSON carries exactly.
	ServicePrincipalID *string `json:"servicePrincipalId,omitempty"`
	// accountId is the Databricks account this identity was made in.
	//
	// Without it, "Databricks says this id does not exist" cannot be told from
	// "I asked the wrong account": both answer 404, and reading the second as
	// the first erases the only record of where a live identity is.
	AccountID *string `json:"accountId,omitempty"`
	// clientId is the applicationId Databricks assigned, which the workload
	// presents when it exchanges its token, and which anything granting
	// permissions to this workload names.
	//
	// It cannot be derived: Databricks generates it and refuses to accept one.
	ClientID *string `json:"clientId,omitempty"`
	// servicePrincipalRemovedAt is when Databricks answered that the service
	// principal above is no longer there.
	//
	// Only the moment, because servicePrincipalId still names it and is not
	// cleared: that id is the value to search Databricks' audit log with, and it
	// says who deleted it and when. What this field decides is whether the
	// identity may still be used, which is Usable.
	ServicePrincipalRemovedAt *v1.Time `json:"servicePrincipalRemovedAt,omitempty"`
	// subject is the sub claim the federation policy matches, assembled from the
	// ServiceAccount's namespace and name.
	//
	// Reported rather than left to be reconstructed: it is what a person compares
	// against a policy in Databricks, and assembling it by hand is where the
	// mistake happens.
	Subject *string `json:"subject,omitempty"`
	// audience is the aud claim on the token this identity is proved with, which
	// its federation policy also names. A token minted for any other audience is
	// refused -- measured -- including the one a pod gets when none is asked for.
	Audience *string `json:"audience,omitempty"`
	// conditions report this identity: whether a token can be exchanged for it,
	// and whether the pods under this ServiceAccount carry what it gave them.
	//
	// Both belong here rather than on the object, and Equipped moved here for a
	// reason worth keeping: with two operators, both would compute it and both
	// would write it, and conditions are keyed by type -- so they would contend
	// for one entry. Asked per identity it also says more, because a pod may
	// carry one operator's token and not another's.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ProjectedIdentityApplyConfiguration constructs a declarative configuration of the ProjectedIdentity type for use with
// apply.
func ProjectedIdentity() *ProjectedIdentityApplyConfiguration {
	return &ProjectedIdentityApplyConfiguration{}
}

// WithProfile sets the Profile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Profile field is set to the value of the last call.
func (b *ProjectedIdentityApplyConfiguration) WithProfile(value string) *ProjectedIdentityApplyConfiguration {
	b.Profile = &value
	return b
}

// WithOperator sets the Operator field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Operator field is set to the value of the last call.
func (b *ProjectedIdentityApplyConfiguration) WithOperator(value string) *ProjectedIdentityApplyConfiguration {
	b.Operator = &value
	return b
}

// WithIssued sets the Issued field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Issued field is set to the value of the last call.
func (b *ProjectedIdentityApplyConfiguration) WithIssued(value string) *ProjectedIdentityApplyConfiguration {
	b.Issued = &value
	return b
}

// WithServicePrincipalID sets the ServicePrincipalID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServicePrincipalID field is set to the value of the last call.
func (b *ProjectedIdentityApplyConfiguration) WithServicePrincipalID(value string) *ProjectedIdentityApplyConfiguration {
	b.ServicePrincipalID = &value
	return b
}

// WithAccountID sets the AccountID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccountID field is set to the value of the last call.
func (b *ProjectedIdentityApplyConfiguration) WithAccountID(value string) *ProjectedIdentityApplyConfiguration {
	b.AccountID = &value
	return b
}

// WithClientID sets the ClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientID field is set to the value of the last call.
func (b *ProjectedIdentityApplyConfiguration) WithClientID(value string) *ProjectedIdentityApplyConfiguration {
	b.ClientID = &value
	return b
}

// WithServicePrincipalRemovedAt sets the ServicePrincipalRemovedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServicePrincipalRemovedAt field is set to the value of the last call.
func (b *ProjectedIdentityApplyConfiguration) WithServicePrincipalRemovedAt(value v1.Time) *ProjectedIdentityApplyConfiguration {
	b.ServicePrincipalRemovedAt = &value
	return b
}

// WithSubject sets the Subject field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Subject field is set to the value of the last call.
func (b *ProjectedIdentityApplyConfiguration) WithSubject(value string) *ProjectedIdentityApplyConfiguration {
	b.Subject = &value
	return b
}

// WithAudience sets the Audience field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Audience field is set to the value of the last call.
func (b *ProjectedIdentityApplyConfiguration) WithAudience(value string) *ProjectedIdentityApplyConfiguration {
	b.Audience = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ProjectedIdentityApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *ProjectedIdentityApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
