apiVersion: databricks.workload-identity.io/v1alpha1
kind: DatabricksAccount
metadata:
  labels:
    app.kubernetes.io/name: databricks-service-principal-operator
    app.kubernetes.io/managed-by: kustomize
  name: databricksaccount-sample
spec:
  # TODO(user): Add fields here
